add_newline = false

[character]
success_symbol = "[󰘧](#118e9c)"

[directory]
style = "#6393e6"
read_only = " "

[username]
show_always = true
style_root = "bold white"
style_user = "#326ba8"
format = "[$user]($style)@"

[hostname]
ssh_only = false
style = "#4d3a99"

[rust]
symbol = ""
format = "[$symbol ($version)]($style) "
style = "#a1710a"

[python]
symbol = "󱔎"
format = "[$symbol ($version)]($style) "
style = "#068f0a"

[fennel]
symbol = "󰚀"
format = "[$symbol ($version)]($style) "
detect_extensions = ['lua', 'fnl']
detect_folders = ['src']
style = "bold white"

[lua]
symbol = ""
format = "[$symbol ($version)]($style) "
detect_extensions = ['lua', 'fnl']
detect_folders = ['lua', 'build', 'lib']
style = "bold blue"
